# Generated by Django 5.1.3 on 2024-11-23 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('productnr', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('revision', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csnr', models.CharField(max_length=30)),
                ('revision', models.CharField(blank=True, max_length=30)),
                ('comment', models.CharField(blank=True, max_length=2000)),
                ('serial_top', models.CharField(blank=True, max_length=30)),
                ('serial_bottom', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('defect', models.BooleanField(default=False, null=True, verbose_name='Defect')),
                ('swversion', models.CharField(blank=True, max_length=30, null=True)),
                ('attachment', models.FileField(upload_to='attachments/board/%Y-%m-%d-%H-%M-%S/')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.boardclass')),
            ],
        ),
        migrations.CreateModel(
            name='BoardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patches', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('location', models.CharField(max_length=50, verbose_name='Current Location')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.board')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('desc', models.CharField(max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.board')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('location', models.CharField(max_length=200)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.board')),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.boardclass')),
            ],
        ),
        migrations.CreateModel(
            name='PatchDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=2000)),
                ('why', models.CharField(blank=True, max_length=2000)),
                ('mandatory', models.BooleanField(null=True, verbose_name='Mandatory')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('mantis', models.CharField(blank=True, max_length=2000)),
                ('attachment', models.FileField(upload_to='attachments/patch/%Y-%m-%d-%H-%M-%S/')),
                ('revision', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.patch')),
            ],
        ),
        migrations.AddField(
            model_name='boardclass',
            name='projectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.project'),
        ),
        migrations.AlterUniqueTogether(
            name='boardclass',
            unique_together={('name', 'revision', 'projectid')},
        ),
    ]
